### PR TITLE
feat: improve NATS message broker exceptions

### PR DESCRIPTION
**Pull request by mattnichols**
# Summary of Changes

* Utilize new Path SDK Exceptions

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by kcpotluri** [comment]
Are we planning to throw any exceptions when the status is FAIL from the responder?

**Comment by mattnichols** [comment]
My goal was just to raise new exceptions. I think that case is already accounted for. If not, then we should address it in another PR.

**Comment by mattnichols** [comment]
@kcpotluri ☝️

**Review by kcpotluri — APPROVED** [review]
LGTM

**Pull request merged**
